(function(){const book=BookRegistry.get('providence-02');if(!book)return;book.journalEntries=[
{id:'mission:c1',page:'c1',title:'Mission',text:'Le Providence a disparu avec vingt-sept hommes. Son manifeste ne mentionne aucun trésor ni cargaison exceptionnelle.'},
{id:'cap:c3',page:'c3',title:'Un cap impossible',text:'Un calfateur affirme avoir vu le Providence cinq jours plus tôt. Il naviguait vers le sud-est, à l’opposé de sa route normale.'},
{id:'tavernier:c5',page:'c5',title:'La légende de l’île',text:'Le tavernier affirme qu’une île attire les marins trop avides et que ceux qui la cherchent finissent par disparaître.',requiresFlag:'tavernkeeperAuthority'},
{id:'cercle:c6',page:'c6',title:'Le cercle noir',text:'Le vieux marin a dessiné un cercle noir fermé dans ta paume. Il t’a conseillé de fuir si tu retrouvais ce signe ailleurs.',requiresFlag:'blackCirclePalm'},
{id:'bracelet:c7',page:'c7',title:'Le bracelet',text:'La femme espagnole pense que personne ne te reverra. Elle t’a donné un bracelet qui augmente ta Force de 2.',requiresFlag:'forceBracelet'},
{id:'agresseur:c9',page:'c9',title:'Le cercle revient',text:'L’homme venu te tuer a parlé d’un trésor qui devait disparaître. Un cercle noir fermé était tatoué sur son poignet.'},
{id:'pirate:c16',page:'c16',title:'Le carnet du pirate',text:'Un pirate a vu le Providence trois nuits plus tôt : aucun signal, cap au sud-est et comportement étrange de l’équipage.'},
{id:'debris:c20',page:'c20',title:'Une preuve dans le courant',text:'Une planche marquée E. Harcourt provient presque certainement du Providence. Le courant indique qu’elle vient du sud ou du sud-est.'},
{id:'nord:north4',page:'north4',title:'Ce que les pirates ont vu',text:'Des pirates ont aperçu un marchand anglais silencieux avec des hommes immobiles à la rambarde. Ils ont eux-mêmes renoncé à l’aborder.'},
{id:'est:east6',page:'east6',title:'Deux lumières vertes',text:'Un assaillant affirme avoir vu le Providence sans lanternes, avec deux lumières vertes sous la coque, semblables à des yeux.'},
{id:'sud:south2',page:'south2',title:'Le Providence au sud-est',text:'Un capitaine marchand a croisé le Providence deux jours plus tôt. Des hommes étaient visibles sur le pont, mais personne n’a répondu aux signaux.'},
{id:'trouve:c21',page:'c21',title:'Le Providence',text:'Le Providence dérive intact et silencieux. De longues marques remontent sa coque comme si quelque chose l’avait entourée et serrée.'},
{id:'depart:c28',page:'c28',title:'Ils ont quitté le navire',text:'Une chaloupe manque. Les cordages ont été détachés proprement : au moins une partie de l’équipage a quitté le Providence volontairement.'},
{id:'dessins:c29',page:'c29',title:'Les dessins du capitaine',text:'Les dessins montrent une masse sous un navire, deux yeux verts, une île, des pierres bleues et un coffre lumineux.'},
{id:'journal:c30',page:'c30',title:'Le premier navire vide',text:'Le Providence avait lui-même trouvé un navire abandonné. Une carte découverte à bord l’a conduit vers l’île. Puis le Providence est devenu à son tour un navire vide.'},
{id:'plage:c34',page:'c34',title:'La chaloupe du Providence',text:'La chaloupe manquante repose sur la plage. Des hommes du Providence ont donc réellement débarqué sur cette île.'},
{id:'piege:c36',page:'c36',title:'Une piste humaine',text:'Le chemin est balisé au couteau et le premier piège utilise du cordage goudronné de navire. Des marins ont aménagé cette route récemment.'},
{id:'survivant:c51',page:'c51',title:'L’homme blanc',text:'Un homme livide a guidé l’équipage vers le trésor. Après sa venue, certains marins disaient encore le voir lorsqu’il n’était plus là.'},
{id:'camp:c52',page:'c52',title:'Vingt-sept noms',text:'Le camp du Providence était organisé pour durer. Vingt-sept noms figurent sur une liste de garde, puis sont barrés peu à peu jusqu’à n’en laisser que six.'},
{id:'carnet:c53',page:'c53',title:'La chaîne des navires',text:'Le carnet confirme le cycle : un navire vide a attiré le Providence vers l’île. Le Providence a ensuite été abandonné. Le trésor a été caché dans sa cale secrète.'},
{id:'retour:c56',page:'c56',title:'Retour à la crique',text:'Le Resolute a dû quitter la crique sous la menace de voiles pirates. Un compagnon a choisi de rester pour t’attendre.'},
{id:'tresor:c58',page:'c58',title:'Le coffre bleu',text:'Le coffre porte le cercle noir. Il contient des dizaines de pierres bleues : le même trésor que plusieurs personnes ont voulu trouver, cacher ou détruire.'}
];})();