(function(){const book=BookRegistry.get('providence-02');if(!book)return;book.journalEntries=[
{id:'mission:c1',page:'c1',title:'Mission',text:'Le Providence a disparu avec vingt-sept hommes. Son manifeste ne mentionne aucun trésor ni cargaison exceptionnelle.'},
{id:'cap:c3',page:'c3',title:'Trois éclats bleus',text:'Un calfateur a vu trois éclats bleus au large juste avant que le Providence change de cap vers le sud-est. Aucun phare connu ne se trouve là.'},
{id:'tavernier:c5',page:'c5',title:'La légende de l’île',text:'Le tavernier affirme que certains navires disparaissent puis sont retrouvés intacts et vides.',requiresFlag:'tavernkeeperAuthority'},
{id:'cercle:c6',page:'c6',title:'Le cercle noir',text:'Le vieux marin a dessiné un cercle noir fermé dans ta paume. Selon lui, si tu cherches des réponses dans ces eaux, il faut suivre ce signe là où il réapparaît.',requiresFlag:'blackCirclePalm'},
{id:'agresseur:c9',page:'c9',title:'Le cercle revient',text:'L’homme venu te tuer a parlé d’un trésor qui devait disparaître. Il a ajouté : « Ce ne sont pas les navires qu’ils veulent. »'},
{id:'pirate:c16',page:'c16',title:'Quelque chose le gardait',text:'Des pirates ont tenté d’approcher le Providence. La mer retenait leur coque, puis une immense ombre les a frappés. Le Providence est resté intact.'},
{id:'debris:c20',page:'c20',title:'L’île recrache les bateaux',text:'Une planche du Providence dérive depuis le sud-est. Un vieux dicton revient : « l’île mange les marins et recrache les bateaux ».'},
{id:'nord:north4',page:'north4',title:'L’île maudite',text:'Un registre pirate note que le Providence faisait cap sur « l’île maudite, celle qu’on contourne même quand le vent nous y pousse ».'},
{id:'trouve:c21',page:'c21',title:'Le Providence',text:'Le Providence dérive intact et silencieux. De longues marques remontent sa coque comme si quelque chose l’avait entourée et serrée.'},
{id:'relance:c28',page:'c28',title:'Un bateau remis à la mer',text:'La barre est amarrée, une voile a été laissée réduite et l’ancre n’est plus à poste. Quelqu’un a volontairement remis le Providence en mer.'},
{id:'appat:c29',page:'c29',title:'La pierre et la carte',text:'Dans la cabine en désordre, une carte parfaitement dépliée et une pierre bleue ont été laissées bien en évidence. Cela ressemble à une mise en scène.'},
{id:'cycle:c30',page:'c30',title:'Le même appât',text:'Le Providence avait lui-même trouvé sur un navire vide une carte et une pierre bleue. Son capitaine a suivi les trois lumières indiquées dessus.'},
{id:'village:c34',page:'c34',title:'L’île des pêcheurs',text:'Nous avons choisi d’enquêter auprès des anciens pêcheurs avant de suivre les trois lumières. Aucun habitant ne vient accueillir les navires.'},
{id:'ravin:c50',page:'c50',title:'Un survivant',text:'Un pêcheur blessé affirme que des hommes très pâles sont venus de la mer. Il a arraché à l’un d’eux une bague au crâne qui semble avoir une signification pour leur groupe.'},
{id:'maisons:c40',page:'c40',title:'Emportés vivants',text:'Les maisons ont été fouillées sans être pillées. Des traces montrent que plusieurs habitants ont été traînés dehors. Aucun corps.'},
{id:'guet:c43',page:'c43',title:'Un homme pâle',text:'Le poste de guet surveillait l’île au sud-est. Un homme anormalement pâle a été surpris près du village la veille de l’attaque puis s’est enfui.'},
{id:'archives:c46',page:'c46',title:'Les pierres bleues',text:'Les anciens registres parlent de pierres bleues sur l’île voisine, de trois lumières et de navires retrouvés vides.'},
{id:'plage:c49',page:'c49',title:'Ils sont repartis par la mer',text:'Les traces montrent que les assaillants ont emporté les habitants vers leurs embarcations, en direction de l’île au sud-est.'},
{id:'journal:c52',page:'c52',title:'Les derniers mots',text:'Le dernier journal du village se termine par : « Ils sont là. Trop nombreux. Je pars aider les autres. »'},
{id:'piste:c53',page:'c53',title:'La même piste',text:'La carte locale et celle du Providence désignent la même île. La pierre bleue ressemble désormais moins à un trésor qu’à un hameçon.'},
{id:'retour:c56',page:'c56',title:'Sauver les hommes',text:'L’objectif a changé : ce n’est plus le Providence que nous cherchons. Ses marins peuvent encore être vivants sur l’île des hommes pâles.'},
{id:'sanctuaire:caveShrine',page:'caveShrine',title:'Le cycle',text:'Les fresques montrent un navire plein d’hommes lié à une créature sous sa coque, le même navire sur une plage marquée de trois points bleus, puis la coque repartant vide avec une carte tandis que des tentacules emportent les marins.',requiresFlag:'caveTruth'},
{id:'captifs:c68',page:'c68',title:'Les captifs',text:'Des prisonniers sont retenus dans le village, parmi eux au moins un marin du Providence.'},
{id:'appat2:c69',page:'c69',title:'Le véritable prix',text:'Les pierres bleues servent d’appât. Le Gardien protège les navires piégés jusqu’à ce que leurs équipages puissent être livrés au culte.'}
];})();